vqa_root: 'C:/Users/AIIntern/Desktop/BlipMyVersion/BLIP/' #followed by train2014/
vg_root: '/export/share/datasets/vision/visual-genome/'
train_files: ['dataInfoFileTest']
ann_root: 'ann_root'

# set pretrained as a file path or an url
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_vqa_capfilt_large.pth'

# size of vit model; base or large
vit: 'base'
batch_size_train: 2 
batch_size_test: 2 
vit_grad_ckpt: False
vit_ckpt_layer: 0
init_lr: 0.00002

image_size: 480

k_test: 128
inference: 'rank'

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 10